### ISSUE TITLE
Attach Giphy API

### ISSUE THREAD

**Issue by hhsnopek** [jmmiller7/Trendy#3]
Create Giphy view w/`imageView`

**Comment by jmmiller7** [comment]
Take a look at the method populateURLS() in SimpleGalleryFragment.java. This was my initial idea in how we can connect your API, but I haven't looked at how your API handles this stuff...

**Comment by jmmiller7** [comment]
Also- we will need to make sure we use the downsampled versions from Giphy to avoid the OutOfMemoryError stuff... some of the regular gifs can be onward of 9mb per item

**Comment by jmmiller7** [comment]
Completed by @hhsnopek
