### ISSUE TITLE
Manage displaying GIF in GUI

### ISSUE THREAD

**Issue by jmmiller7** [jmmiller7/Trendy#4]
We must come up with a viable solution for displaying GIF before we can fully implement the GUI and connect to Giphy API

**Comment by hhsnopek** [comment]
Did a little searching and found this lib: https://github.com/koral--/android-gif-drawable
Using URI's (URLs) https://github.com/koral--/android-gif-drawable/issues/69

**Comment by hhsnopek** [comment]
@jmmiller7, https://github.com/bumptech/glide <- we'll use this, does everything we need!

**Comment by hhsnopek** [comment]
It works :D
